label: Multi Select (Select2)
status: ready
preview: '@dkwds-framed'

context:
  select_multiple_example:
    name: options
    id: js-select2-example1
    label: VÃ¦lg flere muligheder
    options: ""

      