label: Fonts
status: ready
preview: '@dkwds-framed'

context:
  typefaces:
    - id: IBMPlexSans
      name: IBM Plex Sans
      description: |
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque interdum mollis elit, in faucibus mi consectetur vel. In quis scelerisque lectus. Aliquam aliquam gravida lorem at pharetra. Fusce malesuada sed nisl eget interdum. </p>
        <p><em>Nunc eu lorem molestie, pretium eros in, elementum lectus. Donec vitae facilisis mauris. In sed urna ut felis pellentesque tincidunt at quis dolor. Donec sed velit vel massa tempus venenatis vitae vel urna. Duis tincidunt molestie diam sit amet vehicula. Sed non hendrerit ex, et convallis urna.</em></p>
        <p class="small-text">Donec vitae facilisis mauris. In sed urna ut felis pellentesque tincidunt at quis dolor.</p>
