label: Lists
status: ready
preview: '@dkwds-framed'

context:
  lists:
    list_ul: &default_list
      - text: Ordered list
      - text: Ordered list
      - text: Ordered list
      - text: Ordered list
        list_ul: 
          - text: Ordered sublist
          - text: Ordered sublist
          - text: Ordered sublist
    list_ol: &default_list
      - text: Ordered list
      - text: Ordered list
      - text: Ordered list
      - text: Ordered list
        list_ol:
          - text: Ordered sublist
          - text: Ordered sublist
          - text: Ordered sublist

