label: Alerts
status: ready
preview: '@dkwds-framed'
context:
  alert_example:
    items:
      - name: info
        classes: "alert-info"
        role: "alert"
        title: "Informativ besked"
        content: "Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."
        aria: "Beskedbox der viser information"

      - name: success
        classes: "alert-success"
        role: "alert"
        title: Succesmeddelelse
        content: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."
        aria: "Beskedbox der viser succes"
            
      - name: warning
        classes: "alert-warning"
        role: "alert"
        title: Advarsel
        content: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."
        aria: "Beskedbox der viser en advarsel"

      - name: error
        classes: "alert-error"
        role: "alert"
        title: Fejlbesked
        content: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."
        aria: "Beskedbox der viser en fejlmeddelselse"
        
      - name: info with icon
        classes: "alert-info alert--show-icon"
        role: "alert"
        title: "Informativ besked - med ikon"
        content: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."
        aria: "Beskedbox der viser information"

      - name: success with icon
        classes: "alert-success alert--show-icon"
        role: "alert"
        title: "Succesmeddelelse - med ikon"
        content: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."
        aria: "Beskedbox der viser succes"
            
      - name: warning with icon
        classes: "alert-warning alert--show-icon"
        role: "alert"
        title: "Advarsel - med ikon"
        content: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."
        aria: "Beskedbox der viser en advarsel"

      - name: error with icon
        classes: "alert-error alert--show-icon"
        role: "alert"
        title: "Fejlbesked - med ikon"
        content: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium."
        aria: "Beskedbox der viser en fejlmeddelselse"
      
      - name: info no text
        classes: "alert-info alert--show-icon"
        role: "alert"
        title: "Informativ besked - kun overskrift"
        aria: "Beskedbox der viser information"

      - name: Info paragraph
        classes: "alert-info alert--paragraph"
        role: "alert"
        title: Informativ besked - tekstafsnit
        content: "Multi line. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui atione voluptatem sequi nesciunt. Neque porro quisquam est, qui doloremipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."
        aria: "Beskedbox der viser information"