label: Cards
status: ready
preview: '@dkwds-framed'

context:
  cards1_example:
    items:
      - name: "card1"
        header: 'Header'
        subheader: 'Understøttende tekst'
        cardtext: 'Dette er et <em>tekstområde</em>, hvor du kan skrive hvad du har lyst til.'
        cardcontent: '<span class="displayheading-1">Data m.m.</span>'
        actionbuttons: '<button class="button button-secondary">Sekundærknap</button> <button class="button button-tertiary">Tertiærknap</button>'
        actionlinks: '<ul class="unstyled-list"><li><a href="javascript:void(0);" class="default link state">Et link til et sted i løsningen</a></li><li><a href="javascript:void(0);" class="icon-link">Et link til et sted uden for løsningen<svg class="icon-svg "><use xlink:href="#open-in-new"></use></svg></a></li></ul>'
  cards2_example:
    items:
      - name: "card2"
        header: 'Header'
        subheader: 'Understøttende tekst'
        cardcontent: '<span class="displayheading-1">Data m.m.</span>'
        cardtext: 'Dette er et <em>tekstområde</em>, hvor du kan skrive hvad du har lyst til.'    
  cards3_example:
    items:
      - name: "card3"
        cardcontent: '<span class="displayheading-1">Data m.m.</span>'
        header: 'Header'
        subheader: 'Understøttende tekst'
        actionbuttons: '<button class="button button-secondary">Sekundærknap</button> <button class="button button-tertiary">Tertiærknap</button>'
        actionlinks: '<ul class="unstyled-list"><li><a href="javascript:void(0);" class="default link state">Et link til et sted i løsningen</a></li><li><a href="javascript:void(0);" class="icon-link">Et link til et sted uden for løsningen<svg class="icon-svg "><use xlink:href="#open-in-new"></use></svg></a></li></ul>'
  cards4_example:
    items:
      - name: "card4"
        header: 'Header'
        subheader: 'Understøttende tekst'
        cardtext: 'Dette er et <em>tekstområde</em>, hvor du kan skrive hvad du har lyst til.'
        actionbuttons: '<button class="button button-secondary">Sekundærknap</button> <button class="button button-tertiary">Tertiærknap</button>'
        actionlinks: '<ul class="unstyled-list"><li><a href="javascript:void(0);" class="default link state">Et link til et sted i løsningen</a></li><li><a href="javascript:void(0);" class="icon-link">Et link til et sted uden for løsningen<svg class="icon-svg "><use xlink:href="#open-in-new"></use></svg></a></li></ul>'
  cards5_example:
    items:
      - name: "card5"
        header: 'Header'
        subheader: 'Understøttende tekst'
        cardcontent: '<span class="displayheading-1">Data m.m.</span>'
  cards6_example:
    items:
      - name: "card6"
        header: 'Header'
        subheader: 'Understøttende tekst'
        cardtext: 'Dette er et <em>tekstområde</em>, hvor du kan skrive hvad du har lyst til.'    
