label: Side navigation
status: ready

context:
  sidenav:
    links: &default_links
      - text: Parent link
      - text: Current page
        current: true
        links:
          - text: Child link
          - text: Child link
            current: true
            links:
              - text: Grandchild link
              - text: Grandchild link
              - text: Grandchild link
                active: true
              - text: Grandchild link
          - text: Child link
          - text: Child link
          - text: Child link
      - text: Another link

variants:
  - name: default

  - name: compare
    context:
      sidenavsNormal:
        - title: 1 level
          links:
            - text: Parent link
            - text: Current page
              active: true
            - text: Another link

        - title: 2 levels
          links:
            - text: Parent link
            - text: Current page
              current: true
              links:
                - text: Child link
                - text: Child link
                  active: true
                - text: Child link
                - text: Child link
                - text: Child link
            - text: Another link

        - title: 3 levels
          links:
            - text: Parent link
            - text: Current page
              current: true
              links:
                - text: Child link
                - text: Child link
                  current: true
                  links:
                    - text: Grandchild link
                    - text: Grandchild link
                    - text: Grandchild link
                      active: true
                    - text: Grandchild link
                - text: Child link
                - text: Child link
                - text: Child link
            - text: Another link

      sidenavsIcon:
        - title: 1 level
          links:
            - text: Parent link
              iconbefore: message
            - text: Current page
              iconbefore: cash-multiple
              active: true
            - text: Another link
              iconbefore: settings

        - title: 2 levels
          links:
            - text: Parent link
              iconbefore: message
            - text: Current page
              iconbefore: cash-multiple
              current: true
              links:
                - text: Child link
                - text: Child link
                  active: true
                - text: Child link
                - text: Child link
                - text: Child link
            - text: Another link
              iconbefore: settings

        - title: 3 levels
          links:
            - text: Parent link
              iconbefore: message
            - text: Current page
              iconbefore: cash-multiple
              current: true
              links:
                - text: Child link
                - text: Child link
                  current: true
                  links:
                    - text: Grandchild link
                    - text: Grandchild link
                    - text: Grandchild link
                      active: true
                    - text: Grandchild link
                - text: Child link
                - text: Child link
                - text: Child link
            - text: Another link
              iconbefore: settings

      sidenavsInformation:
        - title: 1 level
          links:
            - text: Parent link
              information: Informationstekst for parent link
            - text: Current page
              information: Informationstekst for current link
              active: true
            - text: Another link
              information: Informationstekst for another link

        - title: 2 levels
          links:
            - text: Parent link
              information: Informationstekst for parent link
            - text: Current page
              information: Informationstekst for current link
              current: true
              links:
                - text: Child link
                - text: Child link
                  active: true
                - text: Child link
                - text: Child link
                - text: Child link
            - text: Another link
              information: Informationstekst for another link

        - title: 3 levels
          links:
            - text: Parent link
              information: Informationstekst for parent link
            - text: Current page
              information: Informationstekst for current link
              current: true
              links:
                - text: Child link
                - text: Child link
                  current: true
                  links:
                    - text: Grandchild link
                    - text: Grandchild link
                    - text: Grandchild link
                      active: true
                    - text: Grandchild link
                - text: Child link
                - text: Child link
                - text: Child link
            - text: Another link
              information: Informationstekst for another link

  
