label: Tringuide
status: ready

context:
  tringuiden:
    trinlisten: &default_links
      - text: Trin 1
        information: Informationstekst for trin 1
        icon: check
      - text: Trin 2
        information: Informationstekst for trin 2
        icon: check
      - text: Trin 3 (valgt)
        information: Informationstekst for trin 3
        active: true
      - text: Trin 4
        information: Informationstekst for trin 4
      - text: Trin 5
        information: Informationstekst for trin 5



