label: Eksempel-Boernetilskud - Ansøgning side 1

context:
  portal_header_data:
    user:
      name: 'Christian Emil Vestergaard Christiansen'
    logolink: 
      title: 'Hjem'
      href: 'javascript:void(0);'
      label: 'logo link'
    link:
      href: '#'
      class: 'button-secondary'
      text: 'Log ud'
  solution_header_data:
    title:
      href: '#'
      title: 'Hjem'
      label: 'logo link'
      text: 'Familieydelser - børnetilskud'
    authority:
      name: 'Styrelsen for Eksempler'
      text: 'Tlf.: 33 28 38 38'
  
  title: "Hvilke børn søger du tilskud til?"
  lead: "Brug en af de følgende funktioner, til at administrere børnetilskud:"

  footer_data:
    cols:
      - col:
        col_size_desktop: 6
        text_align_right: false
        lists:
          - list:
            inline_list: false
            listitems:
              - content: '<span class="h5 weight-semibold">Ansvarlig myndighed</span>'
              - content: '<p>Styrelsen for Eksempel</p>'
      - col:
        col_size_desktop: 6
        text_align_right: true
        lists:
          - list:
            inline_list: false
            listitems:
              - content: <a class="function-link" href="mailto:support@example.dk">support@example.dk</a>
              - content: <a class="function-link" href="tel:12 34 56 78">12 34 56 78</a>
