status: ready

context:
  portal_header_data:
    user:
      name: 'Lone hansen'
    logolink: 
      title: 'Hjem'
      href: 'javascript:void(0);'
      label: 'logo link'
    link:
      href: '#'
      class: 'button-secondary'
      text: 'Log ud'
  solution_header_data:
    title:
      href: '#'
      title: 'Hjem'
      label: 'logo link'
      text: 'LÃ¸sningstitel'
    authority:
      name: 'Myndighedsnavn'
      text: 'Support: 12 34 56 78'
