label: Eksempel Digital flytning - Side 5

context:
  portal_header_data:
    user:
      name: 'Navn'
    logolink: 
      title: 'Hjem'
      href: 'javascript:void(0);'
      label: 'logo link'
    link:
      href: '#'
      class: 'button-secondary'
      text: 'Log ud'
  solution_header_data:
    title:
      href: '#'
      title: 'Hjem'
      label: 'logo link'
      text: 'Digital flytning'
    authority:
      name: 'Navn på myndighed'
      text: '<button class="button-unstyled button-contact" data-micromodal-trigger="modal-contact">Kontakt<svg class="icon-svg "><use xlink:href="#menu-right"></use></svg></button>'
  
  modal_contact_data:
    modal_title_id: 'modal-contact-1'
    modal_title: 'Kontakt'
    modal_content: '<div class="alert alert-warning" role="alert" aria-label="Beskedbox der viser en advarsel"><div class="alert-body"><h3 class="alert-heading">Vi har noget information af advarende karakter</h3>          <p class="alert-text">Noget tekst, der forklarer det af advarende karakter, som brugeren bør vide inden denne ringer eller skriver. Noget tekst, der forklarer det af advarende karakter, som brugeren bør vide inden denne ringer eller skriver.</p>        </div>      </div>      <h3>En form for support</h3>      <p>Hvis du har spørgsmål om:</p>      <ul>        <li>En ting som denne</li>        <li>Et andet emne som dette</li>      </ul>        <p>Kan du ringe direkte til: 12 34 56 78</p>      <p>Telefonen er åben:</p>      <p class="m-0">Mandag:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp kl. 9-17</p>      <p class="m-0">Tirsdag-torsdag:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp kl. 9-17</p>      <p class="m-0">Fredag:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp kl. kl. 9-14</p>'
  
    fieldgroup:
    title: Titel på feltgruppe
    text: Indledende brødtekst til feltgruppe Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor.

  footer_data:
      cols:
        - col:
          col_size_desktop: 6
          text_align_right: false
          lists:
            - list:
              inline_list: false
              listitems:
                - content: '<span class="h6 weight-semibold">Ministeriet for Eksempel</span>'
                - content: '<p>Styrelsen for Eksempel</p>'
        - col:
          col_size_desktop: 6
          text_align_right: true
          lists:
            - list:
              inline_list: false
              listitems:
                - content: <a class="" href="mailto:support@example.dk">support@example.dk</a>
                - content: <a class="" href="tel:12 34 56 78">12 34 56 78</a>