label: Modal
status: ready
preview: '@dkwds-framed'

context:
  modal_data_active:
    modal_title_id: 'modal-title-1'
    modal_title: 'Modal'
    modal_content: <p>Modalens indhold. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
    modal_close_text: 'Luk'
    modal_actions: '<button class="button button-primary" aria-label="Fx bekræft handling">Primærknap</button><button class="button button-secondary" data-micromodal-close aria-label="Fx lukker modal vinduet">Sekundærknap</button>'
  modal_data_passive:
    modal_title_id: 'modal-title-2'
    modal_title: 'Modal'
    modal_content: <p>Modalens indhold. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
    modal_close_text: 'Luk'
