label: Tags
status: ready
preview: '@dkwds-framed'

variants:
  - name: default
    label: Examples


context:
  tag_example:
    items:
      - class: ''
        label: 'Tags'
        state: 'default'
      - class: ''
        state: 'hover'
      - class: ''
        state: 'active'
      - class: ''
        state: 'focus'

      - class: ''
        label: 'Tags med ikon'
        state: 'icon-default'
      - class: ''
        state: 'icon-hover'
      - class: ''
        state: 'icon-active'
      - class: ''
        state: 'icon-focus'