label: Checkbox
status: ready
preview: '@dkwds-framed'

context:
  checkbox_example:
    items:
      - id: Unchecked
        name: unchecked
        value: unchecked
        checked: false
        disabled: false
        text: Unchecked

      - id: Checked
        name: checked
        value: checked
        checked: true
        disabled: false
        text: Checked

      - id: disabled
        name: disabled
        value: disabled
        checked: false
        disabled: true
        text: Disabled

      - id: disabled-checked
        name: disabled-checked
        value: disabled-checked
        checked: true
        disabled: true
        text: Disabled checked

      - id: fokus
        name: Focus
        value: fokus
        checked: false
        disabled: false
        focus: true
        text: Focus
        class:

      - id: Unchecked-large
        name: unchecked-large
        value: unchecked-large
        checked: false
        disabled: false
        text: Unchecked-large
        large: true

      - id: Checked-large
        name: checked-large
        value: checked-large
        checked: true
        disabled: false
        text: Checked-large
        large: true

      - id: disabled-large
        name: disabled-large
        value: disabled-large
        checked: false
        disabled: true
        text: Disabled-large
        large: true

      - id: disabled-checked-large
        name: disabled-checked-large
        value: disabled-checked-large
        checked: true
        disabled: true
        text: Disabled-checked-large
        large: true

      - id: fokus-large
        name: Focus-large
        value: fokus-large
        checked: false
        disabled: false
        focus: true
        text: Focus-large
        class:
        large: true
