label: Radio button
status: ready
preview: '@dkwds-framed'

context:
  radiobuttons_example:
    items:
      - id: unchecked
        name: unchecked
        value: truth
        text: Unchecked
        checked: false
        disabled: false

      - id: Checked
        name: Checked
        value: Checked
        text: Checked
        checked: true
        disabled: false

      - id: Disabled
        name: Disabled
        value: Disabled
        text: Disabled
        checked: false
        disabled: true

      - id: Disabled-checked
        name: Disabled-checked
        value: Disabled-checked
        text: Disabled checked
        checked: true
        disabled: true

      - id: Focus
        name: Focus
        value: Focus
        text: Focus
        checked: false
        disabled: false
        focus: true

      - id: Unchecked-large
        name: Unchecked-large
        value: Unchecked-large
        text: Unchecked-large
        checked: false
        disabled: false
        large: true

      - id: Checked-large
        name: Checked-large
        value: Checked-large
        text: Checked-large
        checked: true
        disabled: false
        large: true

      - id: Disabled-large
        name: Disabled-large
        value: Disabled-large
        text: Disabled-large
        checked: false
        disabled: true
        large: true

      - id: Disabled-checked-large
        name: Disabled-checked-large
        value: Disabled-checked-large
        text: Disabled-checked-large
        checked: true
        disabled: true
        large: true

      - id: Focus-large
        name: Focus-large
        value: Focus-large
        text: Focus-large
        checked: false
        disabled: false
        focus: true
        large: true