label: Select
status: ready
preview: '@dkwds-framed'

context:
  select_example:
    name: options
    id: options
    label: Dropdown label (select)
    options:
      - value: "option1"
        text: "Mulighed 1"
      - value: "option2"
        text: "Mulighed 2"
      - value: "option3"
        text: "Mulighed 3"
      