label: Tekst-input
status: ready
preview: '@dkwds-framed'

context:
  textinput_example:
    items:
      - id: input-type-text
        label: Inputfelt med label
        name: input-type-text
        hint: Fx 12345678
      - id: input-focus
        label: Inputfelt i fokus
        class: focus
        name: input-focus
      - id: input-error
        name: input-error
        label: Inputfelt med fejl
        error: Hj√¶lpsom fejlbesked
        hint: Fx 12345678
      - id: input-success
        label: Inputfelt med succes
        success: true
