label: Tekst-area
status: ready
preview: '@dkwds-framed'

context:
  textarea_example:
    items:
      - id: input-area
        label: Tekstområde med label
        name: input-area
      - id: input-error
        label: Tekstområde med fejlbesked
        name: input-area
        error: Hjælpsom fejlbesked
