label: Buttons
status: ready
preview: '@dkwds-framed'

variants:
  - name: default
    label: Examples


context:
  button_example:
    button_groups:
      - button_group:
        label: 'Primær knapper'
        items: 
          - class: 'primary'
            state: 'default'
          - class: 'primary'
            state: 'hover'
          - class: 'primary'
            state: 'active'
          - class: 'primary'
            state: 'focus'
          - class: 'primary'
            state: 'disabled'
      
      - button_group:
        label: 'Sekundær knapper'
        items: 
          - class: 'secondary'
            state: 'default'
          - class: 'secondary'
            state: 'hover'
          - class: 'secondary'
            state: 'active'
          - class: 'secondary'
            state: 'focus'
          - class: 'secondary'
            state: 'disabled'

      - button_group:
        label: 'Tertiær knapper'
        items: 
          - class: 'tertiary'
            state: 'default'
          - class: 'tertiary'
            state: 'hover'
          - class: 'tertiary'
            state: 'active'
          - class: 'tertiary'
            state: 'focus'
          - class: 'tertiary'
            state: 'disabled'
      
      - button_group:
        label: 'Ghost knapper'
        items: 
          - class: 'ghost'
            state: 'default'
          - class: 'ghost'
            state: 'hover'
          - class: 'ghost'
            state: 'active'
          - class: 'ghost'
            state: 'focus'
          - class: 'ghost'
            state: 'disabled'
      
      - button_group:
        label: 'Knap med ikon'
        items: 
          - class: 'primary'
            state: 'icon'
