label: Accordion
status: ready
preview: '@dkwds-framed'

variants:
  - name: default

context:
  accordion_example:
    label: Borderless
    items:
      - title: Lorem ipsum dolor sit amet
        id: a1
        icon: info
        icontext: Information
        expanded: false
        content: |
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      - title: Consectetur adipiscing elit
        id: a2
        icon: close-circle-outline
        icontext: Fejl
        error_message: true
        content: |
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
      - title: Sed do eiusmod tempor
        id: a3
        icon: alert-outline
        icontext: Advarsel
        content: |
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
      - title: Labore et dolore magna
        id: a4
        icon: check-circle-outline
        icontext: Succes
        content: |
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
      - title: Ut enim ad minim veniam
        id: a5
        icon:
        icontext:
        content: |
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
  
  accordion_example2: 
    label: bordered
    id_prefix: b-
    variant: bordered
    items:
      - title: Lorem ipsum dolor sit amet
        id: a1
        icon: info
        icontext: Information
        expanded: false
        content: |
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      - title: Consectetur adipiscing elit
        id: a2
        icon: close-circle-outline
        icontext: Fejl
        error_message: true
        content: |
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      - title: Sed do eiusmod tempor
        id: a3
        icon: alert-outline
        icontext: Advarsel
        content: |
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      - title: Labore et dolore magna
        id: a4
        icon: check-circle-outline
        icontext: Succes
        content: |
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      - title: Ut enim ad minim veniam
        id: a5
        icon:
        icontext:
        content: |
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

  accordion_example3: 
    id_prefix: m-
    multiselectable: true
    items:
      - title: Lorem ipsum dolor sit amet
        id: a1
        icon: info
        icontext: Information
        expanded: false
        content: |
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      - title: Consectetur adipiscing elit
        id: a2
        icon: close-circle-outline
        icontext: Fejl
        error_message: true
        content: |
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      - title: Sed do eiusmod tempor
        id: a3
        icon: alert-outline
        icontext: Advarsel
        content: |
         Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      - title: Labore et dolore magna
        id: a4
        icon: check-circle-outline
        icontext: Succes
        content: |
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      - title: Ut enim ad minim veniam
        id: a5
        icon:
        icontext:
        content: |
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.